# Define the database type
quarkus.datasource.db-kind=mysql

# Database Connection Credentials
quarkus.datasource.username=operator
quarkus.datasource.password=passw0rd

# JDBC Connection URL
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/phonebook_db?serverTimezone=UTC

# Hibernate ORM (Optional - if using Hibernate/Panache)
quarkus.hibernate-orm.log.sql=true
